### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dsterna** [magello-group/evoAppen#1]
**High Priority:**

- [ ] Add Template (don't forget to store userId of template maker so he/she can edit)
- [ ] Edit Round (use same component as new-round, check for edit param from useRoutes and do a fetch)
- [x] Delete Round (Have delete option in table drop down)
- [x] Mandatory motivations are not set properly when creating round
- [ ] Rename pages and components to consistent convention (PascalCase)
- [ ] In EditRound, the description is hardcoded and not from apiData.

**Medium Priority:**

- [ ] Add names of authenticated users in landing page table. If a konsultchef wants to find specific employees' rounds, it should be possible, maybe even searchable.
- [ ] Clean Up old ToDo infra and code
- [ ] Check for Type mismatch between FE and API
- [ ] Stop user from accidentally leaving the page when filling out editRound form. Maybe use "beforeunload"
- [ ] Color Schemes for user answers and Score colors
- [ ] Button to add link to clipboard
- [ ] Dropdown in landing page table has dead spots. You now have to press in the middle of option

**Low Priority:**

- [ ] Create "Om evoAppen" dialog and text
- [ ] Table for My Templates (to edit and remove templates)
- [ ] Have a maximum answers option
- [x] Dropdown option in SpiderChart to get mean value of all users combined.
